### ISSUE TITLE
SSL handshake issues

### ISSUE THREAD

**Issue by bre7** [eggheadgames/Siren#10]
I've been having some issues on older devices (E.g: KitKat) when the json file is accessed using HTTPS on a server that doesn't support SSL3. The solution is to force HttpsURLConnection's ciphers: http://stackoverflow.com/a/30302235/2124535

Supported ciphers per platform: https://developer.android.com/reference/javax/net/ssl/SSLSocket.html

PR sent

**Comment by mikemee** [comment]
@bre7 Thanks Nathan. Apologies that took a month, but we finally merged and released a new version _(as you probably noticed, judging by the 👍 I saw)_.

It also highlighted a problem where our CI config doesn't build PRs from outside repos. We'll dig into that when we get the next PR from someone :)  We didn't want to sidetrack on that right now!

Thanks again, Mike @ Egghead Games

**Comment by bre7** [comment]
No worries, I'm on holidays too (most of the week). I'm just glad it was merged and thanks for the message 😉

**Comment by mikemee** [comment]
@bre7 Note that we took another go at this in #14 and #15 - we hadn't tested http with the PR, and our apps currently have an http backed (tsk tsk).

If you can eyeball the code in #15 and confirm that you're still happy with it, that would be great. Thx!
