### ISSUE TITLE
Can I set the dialog title and content by myself?

### ISSUE THREAD

**Issue by OnlyMyRailgun** [eggheadgames/Siren#17]

**Comment by mikemee** [comment]
You can either:

1. just use the notifications to trigger whatever custom things you'd like to show (i.e. not use the provided dialogs at all), or
2. use the provided dialogs and then override the strings that are included by providing the same named strings in your app's `res/strings.xml` file.

Note that for the (2) scenario, there are already localisations for many languages, so it would fall back to those versions unless you also override them with your own.

Make sense?
