### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by pirishd** [eggheadgames/Siren#19]
There does not seem to be Chinese language support in the library contrary to what the documentation says: https://github.com/eggheadgames/Siren#localization. 

Am I right? Is the support of this language planned?

**Comment by mikemee** [comment]
Hi @pirishd , we should have all the languages that the iOS Siren supports, but perhaps we missed some, or they were added between when we created the code and copied and modified the documentation.

If you can tell me which ones here: https://github.com/ArtSabintsev/Siren/tree/master/Sources/Siren.bundle that you need, and what the equivalent Android language code(s) are, we can add them.

Or, of course, feel free to give us a PR based on the translations you can see at https://github.com/ArtSabintsev/Siren/tree/master/Sources/Siren.bundle.

Thanks!

**Comment by pirishd** [comment]
Hi @mikemee, I created a PR to add the support of the Chinese language (based on the translations found in https://github.com/ArtSabintsev/Siren/blob/master/Sources/Siren.bundle/zh-Hans.lproj/SirenLocalizable.strings).

Would you please review that?

**Comment by mikemee** [comment]
@pirishd Thanks! Let's continue in the PR, where I have a question.

**Comment by mikemee** [comment]
@pirishd Many thanks for the issue and PR. This was fixed in release 1.4.8.
