### ISSUE TITLE
Buttons layout with long translated strings

### ISSUE THREAD

**Issue by pirishd** [eggheadgames/Siren#23]
For languages with long strings in buttons (like French or Russian), text is cut.

See attached screenshot for the French translation of "Next Time" ("La prochaine fois")

![screenshot](https://user-images.githubusercontent.com/28482872/30519355-b9372bc0-9b94-11e7-9a7d-fc4456f6f6c6.png)

**Comment by pirishd** [comment]
See PR #24 :)

**Comment by mikemee** [comment]
Fixed in #24
