### ISSUE TITLE
Support parsing of additional parameters on the JSON file

### ISSUE THREAD

**Issue by saraht129** [eggheadgames/Siren#25]
Hello,

I'm using this library alongside with the iOS counterpart, and I'm planning on using the same JSON file for both. Other than setting minVersionCode, I would also like to toggle version check and set alertType from that. While I can do parsing manually on iOS, I wonder if there's a way to retrieve the additional parameters on Android, since I don't have to handle download & parsing here?

Thank you!

**Comment by mikemee** [comment]
@saraht129 that's a great idea. The source is there. If you have a specific suggestion on how to implement this (another API call or callback to return the previous fetched JSON perhaps?), or, even better, a PR, I'll definitely look at it.
