### ISSUE TITLE
Dialog Title "Update Available"

### ISSUE THREAD

**Issue by janicelco** [eggheadgames/Siren#37]
Dialog title is only showing on Android 5 device.
I have run the code on:
Samsung Note 3, Android 5.0.1 (Shows title)
Nexus 7, Android 6.0.1 (No title)
Samsung S6, Android 7.0.1 (No title)

How to i ensure that the title is showing on all devices?

**Comment by mikemee** [comment]
Do you happen to have screenshots?  Thanks!

**Comment by janicelco** [comment]
Android 5:
![android_5](https://user-images.githubusercontent.com/23180161/33582811-0eaad9e0-d992-11e7-987d-e6554e2b8f03.png)

Android 7:
![android_7](https://user-images.githubusercontent.com/23180161/33582817-159c9748-d992-11e7-8e69-b62b5db0d5b2.png)

We are using Japanese text not by localisation as our client wants a different text. I have override the strings.

**Comment by mikemee** [comment]
Thanks, we'll take a look. I remember some similar weirdness with Android dialogs in a different scenario. 

@Apisov @AlexDibrivnyy any ideas?

**Comment by mikemee** [comment]
@janicelco you could always import the source code directly from this library and try it 👍

**Comment by mikemee** [comment]
@janicelco This should be fixed for [release 1.5.2](https://github.com/eggheadgames/Siren/releases/tag/1.5.2). Please double check and let us know. Thanks!

**Comment by janicelco** [comment]
@mikemee Thanks! Checked it for Android 7.0. Its now showing. =)
