### ISSUE TITLE
[solved]custom configurations ignored...cant set dialog to "force"

### ISSUE THREAD

**Issue by Xstar97** [eggheadgames/Siren#5]
I tried multiple ways & even followed the sample to the letter, but I can't set my dialog to "force" so I can finally "force" my users to install the latest updates....it keeps using the default settings...the two button dismiss & update!
this is the only library that worked for me & its the simplest...but it just won't let me set my own configurations what so ever

I also even changed my json file from version name to versioncode just to be sure...but its still the same problem

**Comment by mikemee** [comment]
Thanks Xstar97, We'll take a look at this pronto. Just in case it helps, do you have a code snippet you can share?  Thx.

**Comment by mikemee** [comment]
Fwiw, I created the screenshots by using the various options, so it was working to some extent...

**Comment by mikemee** [comment]
@yurii-diachenko can you please take a look, and also create a test to cover the `FORCE` scenario (and similar)? Thx.

**Comment by Xstar97** [comment]
//above oncreate
private static final String TAG = MainActivity.class.getSimpleName();
    private static final String SIREN_JSON_DOCUMENT_URL = "https://raw.githubusercontent.com/Xstar97/TXI/master/gandalf.json";
//inside on create
checkCurrentAppVersion();
....
}

	private void checkCurrentAppVersion() {
		Siren siren = Siren.getInstance(getApplicationContext());
        siren.setMajorUpdateAlertType(SirenAlertType.FORCE);
		siren.checkVersion(this, SirenVersionCheckType.IMMEDIATELY, SIREN_JSON_DOCUMENT_URL);
    }

**Comment by mikemee** [comment]
@Xstar97, and what is the current version of your app?  I wonder if adding the following will get the bahaviour you want:
```
siren.setMajorUpdateAlertType(SirenAlertType.FORCE);
siren.setMinorUpdateAlertType(SirenAlertType.FORCE);
siren.setPatchUpdateAlertType(SirenAlertType.FORCE);
siren.setRevisionUpdateAlertType(SirenAlertType.FORCE);
```
In the meantime, we'll check the logic for Major when using `minVersionCode` in the json file. Thx.

**Comment by Xstar97** [comment]
The version Code is 4, but my json states 5 for testing purposes

**Comment by Xstar97** [comment]
its still the same...config is still not working me...is it working with you?

**Comment by Xstar97** [comment]
private static final String TAG = MainActivity.class.getSimpleName();

in this line "TAG" is yellow...does this have any merit in the error or no?

**Comment by Xstar97** [comment]
also I cant add any older version to my build.gradle...in aide

**Comment by mikemee** [comment]
Thanks for that extra info. I've replicated this behaviour. Now I'm trying to work out why it's broken. I expect to update here shortly... _though my laptop battery is running out...!_

**Comment by Xstar97** [comment]
Thanks! Glad to have help an awesome library!
Even though it's the only one that didn't crash my app...
I tried the others... They didn't work for me

**Comment by mikemee** [comment]
In the meantime, I know you switched to using `versionCode`, but can you try the full semantic version again, i.e.: remove the `versionCode` from the json, replace it with `minVersionName` and try again with all the `setPatchUpdateAlertType` calls above? I know that worked for me in prior testing and that might get you going sooner than waiting for me to get a fix done. Thx!

**Comment by Xstar97** [comment]
Your solution worked for me thanks...Your a life saver!

**Comment by mikemee** [comment]
Thanks. Glad it is working for you now, and thanks for reporting this and the prompt responses!

I think we still need to either more clearly document the current behaviour and/or fix the `versionCode` scenario as well as possibly add some tests, so I'll leave this open until we do.

**Comment by mikemee** [comment]
@Apisov, please take a look at this. thx!

**Comment by mikemee** [comment]
@Xstar97 Did you try using `siren.setVersionCodeUpdateAlertType(SirenAlertType.FORCE);`

I sort of assumed that so I didn't ask, but now that we're testing, it seems that it works as expected. Maybe we just need to update the documentation to fix this!

**Comment by mikemee** [comment]
I've confirmed that this appears to work as requested:
```java
    private void checkAvailableVersion() {
        Siren siren = Siren.getInstance(getApplicationContext());
        siren.setVersionCodeUpdateAlertType(SirenAlertType.FORCE);
        siren.checkVersion(this, SirenVersionCheckType.IMMEDIATELY, SIREN_JSON_DOCUMENT_URL);
    }
```
