### ISSUE TITLE
request: check and show "You have the latest" dialog

### ISSUE THREAD

**Issue by Xstar97** [eggheadgames/Siren#6]
its me again...annoying...right?
So I was wondering since I am able to check if my app has an update & if there is show an update dialog...but if there isn't an update then a no update dialog pops up saying "you have the latest update....blah blah"
it will be cool if this was an extra option...
could you also add this in the next update?

**Comment by mikemee** [comment]
Hi. Not annoying at all. We appreciate the interest!

I'm not inclined to add this feature at the moment, as one of the goals is to keep compatibility with the iOS library of the same name. 

That said, I think you could emulate this behaviour yourself by adding a listener. Though, as I look at it, it might be tricky to detect the "no update" case. 

I'll take another look at siren for iOS to be sure, but my inclination is to leave it for now.  

_(Btw, almost done with a fix for the issue you raised yesterday, thanks!)_

**Comment by Xstar97** [comment]
thats awesome cant wait for the new update!

**Comment by mikemee** [comment]
I've checked, and the iOS version of Siren doesn't have this, so we're going to not add it for the moment.  However, we'll definitely keep it in mind for the future.
