### ISSUE TITLE
Handle alerts yourself.

### ISSUE THREAD

**Issue by siddimania** [eggheadgames/Siren#9]
I just want the versionCode from JSON URL. Is it possible to get in the listener ?

**Comment by siddimania** [comment]
so I missed one thing : I can get it from the message in this `onDetectNewVersionWithoutAlert` but is it possible to get only the versionCode ?

**Comment by mikemee** [comment]
Hi @siddimania - like the the package we emulate, https://github.com/ArtSabintsev/Siren, we don't actually pass through either the version code from the current app, or what was found in the JSON. 

However, you can control whether the app responds to major, minor, patch or revision changes (the 4 digits of an x.x.x.x version number), and, you'll also receive a localised message string to display.

I'm happy to consider extra functionality, though I am biased towards keeping close to what the original iOS library does.

**Comment by siddimania** [comment]
got it, I found a workaround, thanks
